/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/0MiWY0tBaGm
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Chivo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export default function Home() {
  return (
    <main className="container mx-auto grid grid-cols-1 gap-6 p-4 sm:grid-cols-2 lg:grid-cols-3">
      <div className="relative overflow-hidden rounded-lg shadow-lg transition-transform duration-300 ease-in-out hover:-translate-y-2 hover:shadow-xl">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">View</span>
        </Link>
        <img src="/bijli.png" alt="Feature 1" width={100} height={100} className="h-64 w-full object-cover" />
        <div className="bg-background p-4">
          <h3 className="text-lg font-semibold">Electricity Department</h3>
        </div>
      </div>
      <div className="relative overflow-hidden rounded-lg shadow-lg transition-transform duration-300 ease-in-out hover:-translate-y-2 hover:shadow-xl">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">View</span>
        </Link>
        <img src="/placeholder.svg" alt="Feature 2" width={300} height={400} className="h-64 w-full object-cover" />
        <div className="bg-background p-4">
          <h3 className="text-lg font-semibold">Feature 2</h3>
        </div>
      </div>
      <div className="relative overflow-hidden rounded-lg shadow-lg transition-transform duration-300 ease-in-out hover:-translate-y-2 hover:shadow-xl">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">View</span>
        </Link>
        <img src="/placeholder.svg" alt="Feature 3" width={500} height={300} className="h-64 w-full object-cover" />
        <div className="bg-background p-4">
          <h3 className="text-lg font-semibold">Feature 3</h3>
        </div>
      </div>
      <div className="relative overflow-hidden rounded-lg shadow-lg transition-transform duration-300 ease-in-out hover:-translate-y-2 hover:shadow-xl">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">View</span>
        </Link>
        <img src="/placeholder.svg" alt="Feature 4" width={400} height={400} className="h-64 w-full object-cover" />
        <div className="bg-background p-4">
          <h3 className="text-lg font-semibold">Feature 4</h3>
        </div>
      </div>
      <div className="relative overflow-hidden rounded-lg shadow-lg transition-transform duration-300 ease-in-out hover:-translate-y-2 hover:shadow-xl">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">View</span>
        </Link>
        <img src="/placeholder.svg" alt="Feature 5" width={600} height={300} className="h-64 w-full object-cover" />
        <div className="bg-background p-4">
          <h3 className="text-lg font-semibold">Feature 5</h3>
        </div>
      </div>
      <div className="relative overflow-hidden rounded-lg shadow-lg transition-transform duration-300 ease-in-out hover:-translate-y-2 hover:shadow-xl">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">View</span>
        </Link>
        <img src="/placeholder.svg" alt="Feature 6" width={300} height={400} className="h-64 w-full object-cover" />
        <div className="bg-background p-4">
          <h3 className="text-lg font-semibold">Feature 6</h3>
        </div>
      </div>
    </main>
  )
}
